### ISSUE TITLE
use with tail -f

### ISSUE THREAD

**Issue by felixbarny** [koenbollen/jl#13]
Is it possible to use jl in combination with tailing a log file? I tried `tail -f <file> | jl` but without success. The new log lines don't appear.

**Comment by koenbollen** [comment]
He @felixbarny, using `jl` with `tail -f` should work fine. I use that all the time myself (also use it alot with tail logs from docker or k8s).
I just tried it in an isolated environment and it seems to be working just fine.

Does re-running `cat <file> | jl` do properly format the (new) messages?

Could you maybe supply me with the steps to reproduce your issue?

**Comment by felixbarny** [comment]
It's working now, I don't know what I did wrong.
