### ISSUE TITLE
jl can't decode journald format?

### ISSUE THREAD

**Issue by hydrargyrum** [koenbollen/jl#28]
`journalctl -xeu apache2.service -ojson` outputs line like:
```
{
  "_EXE": "redacted",
  "_SYSTEMD_UNIT": "redacted",
  "__REALTIME_TIMESTAMP": "1685990670366836",
  "_TRANSPORT": "redacted",
  "SYSLOG_TIMESTAMP": "redacted",
  "_SYSTEMD_INVOCATION_ID": "redacted",
  "_SYSTEMD_SLICE": "redacted",
  "_CMDLINE": "redacted",
  "_RUNTIME_SCOPE": "redacted",
  "_BOOT_ID": "redacted",
  "__CURSOR": "redacted",
  "__MONOTONIC_TIMESTAMP": "17885855746439",
  "_COMM": "redacted",
  "_PID": "redacted",
  "PRIORITY": "4",
  "MESSAGE": "redacted",
  "_GID": "redacted",
  "SYSLOG_FACILITY": "redacted",
  "_HOSTNAME": "redacted",
  "_MACHINE_ID": "redacted",
  "_CAP_EFFECTIVE": "redacted",
  "_SYSTEMD_CGROUP": "redacted",
  "_SELINUX_CONTEXT": "redacted",
  "_SOURCE_REALTIME_TIMESTAMP": "redacted",
  "SYSLOG_IDENTIFIER": "redacted",
  "_UID": "redacted"
}
```

`journalctl -k -ojson` (for kernel) outputs lines like:

```
{
  "__MONOTONIC_TIMESTAMP": "redacted",
  "_TRANSPORT": "redacted",
  "SYSLOG_FACILITY": "redacted",
  "_BOOT_ID": "redacted",
  "SYSLOG_IDENTIFIER": "redacted",
  "_SOURCE_MONOTONIC_TIMESTAMP": "redacted",
  "__CURSOR": "redacted",
  "_MACHINE_ID": "redacted",
  "PRIORITY": "redacted",
  "__REALTIME_TIMESTAMP": "redacted",
  "_RUNTIME_SCOPE": "redacted",
  "MESSAGE": "redacted",
  "_HOSTNAME": "redacted"
}
```

These formats don't seem understood by `jl` which outputs only blank lines

**Comment by koenbollen** [comment]
Hey @hydrargyrum, thanks for submitting this issue. Should be really straight forward to support this format?
Couple of questions:
1. Does _journald_ output these json object on one line always? (your examples are formatted over multiple lines)
2. Is `"PRIORITY"` the loglevel? And could you give a list of possible values?
3. Which timestamp is most relevant for the log entry?
5. Are there any fields paticulairly interesting? For example, always show SYSLOG_IDENTIFIER or something?
6. Would it make sense to format the fields a bit? e.g. _HOSTNAME become 'hostname' in the output.

It would also help a lot of you have an example where the redaction is a little less strong. (do, of course, make sure there is no sensitive information in there).

**Comment by hydrargyrum** [comment]
1. yes. `-o json` gives one log per line, I reformatted them for readability

I'm not the most knowledgeable on journald format, but starting from [some docs](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html) and experimenting, I'd say

2. `PRIORITY` is the same as syslog, 0-7 (corresponding to emerg, alert, crit, error, warning, notice, info, debug)
3. `_SOURCE_REALTIME_TIMESTAMP` is described as "trusted" but from my tests, it's not always present… `__REALTIME_TIMESTAMP` seems always present though
4. `SYSLOG_IDENTIFIER` seems to be the source program of the log, indeed it can be useful but if viewing logs of a single app it can be repetitive
5. I confess I don't know

With less redaction:
```
{
        "_CAP_EFFECTIVE" : "xxx",
        "MESSAGE_ID" : "xxx",
        "_COMM" : "systemd",
        "SYSLOG_IDENTIFIER" : "systemd",
        "CODE_LINE" : "xxx",
        "_SOURCE_REALTIME_TIMESTAMP" : "xxx",
        "_SYSTEMD_CGROUP" : "/init.scope",
        "_HOSTNAME" : "xxx",
        "_BOOT_ID" : "xxx",
        "TID" : "1",
        "JOB_TYPE" : "start",
        "MESSAGE" : "Starting apache2.service - The Apache HTTP Server...",
        "UNIT" : "apache2.service",
        "_SELINUX_CONTEXT" : "unconfined\n",
        "_TRANSPORT" : "journal",
        "__CURSOR" : "s=xxx",
        "_SYSTEMD_SLICE" : "-.slice",
        "SYSLOG_FACILITY" : "3",
        "_GID" : "0",
        "_SYSTEMD_UNIT" : "init.scope",
        "INVOCATION_ID" : "xxx",
        "JOB_ID" : "xxx",
        "CODE_FILE" : "src/core/job.c",
        "_UID" : "0",
        "_RUNTIME_SCOPE" : "system",
        "CODE_FUNC" : "job_emit_start_message",
        "PRIORITY" : "6",
        "_EXE" : "/usr/lib/systemd/systemd",
        "_CMDLINE" : "/lib/systemd/systemd --system --deserialize 38",
        "__REALTIME_TIMESTAMP" : "xxx",
        "_MACHINE_ID" : "xxx",
        "__MONOTONIC_TIMESTAMP" : "xxx",
        "_PID" : "1"
}
{
        "__CURSOR" : "s=xxx",
        "_EXE" : "/usr/sbin/apache2",
        "_STREAM_ID" : "xxx",
        "_COMM" : "apache2",
        "_GID" : "0",
        "_MACHINE_ID" : "xxx",
        "__REALTIME_TIMESTAMP" : "xxx",
        "__MONOTONIC_TIMESTAMP" : "xxx",
        "_SYSTEMD_SLICE" : "system.slice",
        "PRIORITY" : "6",
        "_HOSTNAME" : "xxx",
        "_BOOT_ID" : "xxx",
        "_TRANSPORT" : "stdout",
        "_CAP_EFFECTIVE" : "xxx",
        "_SELINUX_CONTEXT" : "unconfined\n",
        "MESSAGE" : "AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message",
        "SYSLOG_IDENTIFIER" : "apachectl",
        "_SYSTEMD_UNIT" : "apache2.service",
        "_PID" : "xxx",
        "_SYSTEMD_INVOCATION_ID" : "xxx",
        "SYSLOG_FACILITY" : "3",
        "_CMDLINE" : "/usr/sbin/apache2 -k start",
        "_RUNTIME_SCOPE" : "system",
        "_SYSTEMD_CGROUP" : "/system.slice/apache2.service",
        "_UID" : "0"
}
```

If you're running linux with systemd, you can have examples easily with `journalctl -xe -ojson`

**Comment by koenbollen** [comment]
Awesome, perfect. Thanks.
|I'll try and find some time in coming weeks to add support for this format.

**Comment by koenbollen** [comment]
Hey @hydrargyrum,
I've created a pull request which add basic support for journald.
Would you mind testing it for me? You have more actual experience and knowledge using journald's json output.

They easiest way to install `jl` from this pull request is to run this command (with [Go](https://go.dev/) installed):
```bash
go install github.com/koenbollen/jl@support-journald
```

Let me know if you run into any issues or unexpected outputs. 👍🏻

**Comment by koenbollen** [comment]
I merged the changes and released `jl` on the homebrew tap. Hope it benefits your flow!
