### ISSUE TITLE
1.6.0 release is 1,6,0

### ISSUE THREAD

**Issue by ddeville** [koenbollen/jl#32]
Looks like the release name is incorrectly `1,6,0` rather than `1.6.0` https://github.com/koenbollen/jl/releases/tag/v1%2C6%2C0.

I ran into this when I tried making a new version of the AUR package https://aur.archlinux.org/packages/jl but it's also breaking the [homebrew formula](https://github.com/koenbollen/homebrew-public/blob/HEAD/Formula/jl.rb#L4).

I imagine it's simply a mistake? :)

**Comment by koenbollen** [comment]
> I imagine it's simply a mistake? :)

:trollface:  No, this was on purpose! I meant to use commas... 😂 I wish. My bad... we need pull-requests for making tags..

I'll try and fix it as soon as possible!

**Comment by koenbollen** [comment]
Was an easy edit to fix this. 👍🏻 Thanks for heads up!

**Comment by koenbollen** [comment]
Hey @ddeville, I was thinking. Would it be a good idea to add the install instructions for archlinux in the `jl` readme? I never used arch, so I'm not sure what people there are used to. But if you take the effort of keeping it up to date at AUR we might as well add it to the project readme right?
