### ISSUE TITLE
Include PATH in installation instructions

### ISSUE THREAD

**Issue by scato** [koenbollen/jl#8]
Hi, awesome tool, thnx!

I don't normally work with Golang, so the go bin folder was not on my PATH yet. This means that I followed the installation instructions, but it didn't work.

Adding

```
PATH="~/go/bin:$PATH"
```

to my .bash_profile did the trick of course.

Could you include that in the README?

**Comment by koenrh** [comment]
Agreed, that should be included in the README.

I would add something like this:

>Make sure you have set up your `$GOPATH` correctly, and you have included
>`$GOPATH/bin` in your `$PATH`, then run the following command.

And then link to (or add?) some documentation on how to set up `$GOPATH`.

**Comment by koenbollen** [comment]
I do not intend for most users to use go to install. That is actaully only useful for golang developers and they will already have that setup. 👌 

I'll work on getting it installable via brew.
